apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pv-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pv
  template:
    metadata:
      labels:
        app: nginx-pv
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-storage
        persistentVolumeClaim:
          claimName: nginx-pvc
